#!/usr/bin/ruby

# Copyright 2013 Luke Quinane
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

filename = "/var/lib/munin/state/online_computers"
computers = [] 
current_computers = [] 

File.open(filename, 'r').each_line do |line|
  line = line.strip
  computers << line
end

if ARGV[0] == "config"
  puts "graph_title Online Computers"
  puts "graph_category network"

  first = true

  computers.each do |computer| 
    puts "#{computer}.label #{computer}"

    if first
        puts "#{computer}.draw AREA"
        first = false
    else
        puts "#{computer}.draw STACK"
    end
  end

  exit
end

output = `nmap -sP 10.1.1.1/24`

#Nmap scan report for router (10.1.1.1)
host = ""

output.each_line do |line|
  if line =~ /^Nmap scan report for .+ \(.+/
      host = line.scan(/^Nmap scan report for (.+) \(.+/)[0][0]
      host = host.gsub(/\./, "-")
      host = host.gsub(/[^\w\d-]+/, "")

      computers << host
      current_computers << host
      puts "#{host}.value 1"

  elsif line =~ /^Nmap scan report for .+/
      host = line.scan(/^Nmap scan report for (.+)/)[0][0]
      host = host.gsub(/\./, "-")
      host = host.gsub(/[^\w\d-]+/, "")

      computers << host
      current_computers << host
      puts "#{host}.value 1"
  end
end

computers = computers.uniq

computers.each do |computer|
  if !current_computers.include? computer
    puts "#{computer}.value U"
  end
end

File.open(filename, 'w+') do |file|
  file.puts computers 
end
