#!/usr/bin/ruby

# Copyright 2013 Luke Quinane
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

filename = "/var/lib/munin/state/wifi_channels"
channels = [] 
current_channels = [] 

File.open(filename, 'r').each_line do |line|
  line = line.strip
  channels << line
end

if ARGV[0] == "config"
  puts "graph_title Wifi Channels"
  puts "graph_category network"

  channels.each do |channel| 
    puts "#{channel}.label #{channel}"
    puts "#{channel}.draw LINE1"
  end

  exit
end

output = `sudo /sbin/iwlist eth1 scan`

# ESSID:"ChilliNet"
# Quality:2/5  Signal level:-76 dBm  Noise level:-92 dBm
ssid = ""

output.each_line do |line|
  if line =~ /^\s+ESSID:/
      ssid = line.scan(/^\s+ESSID:"(.+)"/)[0][0]
      ssid = ssid.gsub(/[^\w\d]+/, "")

      channels << ssid
      current_channels << ssid
  end
  if line =~ /Signal level:/
      power = line.scan(/Signal level:(-\d+)/)[0][0]
      puts "#{ssid}.value #{power}"
  end
end

channels = channels.uniq

channels.each do |channel|
  if !current_channels.include? channel
    puts "#{channel}.value U"
  end
end

File.open(filename, 'w+') do |file|
  file.puts channels
end
